### ISSUE TITLE
HUGE UPDATE! (update rating)

### ISSUE THREAD

**Issue by ghost** [ZeusHay/Synapse-X-Infinity#4]
(REGARDING UPDATE 0.0.3A)
If you are currently working on the UI, I advise you to read this after you're done or after your break.

I love this new update.

I've noticed in this update (without looking at the updates) I see that you are now able to change the icons. Personally, I don't think this is a big deal because I like how they are, but I still will use it just in case I just want the original synapse logo.

Border and Logo Text is pretty cool. I will be using those a lot. But I have noticed a problem with them, it appears they don't save. Are you able to create an SXI bin folder for SXI instead of synapse? Just to save data in, you may be using that later on, for the rest of the toggles and stuff.

Thanks for fixing Auto Inject by the way.

I have noticed you've added something called Hydroxide. I have never seen this remote spy before and I am ashamed of myself for not seeing it. This remote spy is amazing and I will use it from now on instead of Frost Hook and Simple Spy.

Oh, and I have noticed the rest of the settings.
(from this point on I will be looking at the stuff I missed)
I just missed one thing surprisingly. Just the style redesign, also I love the animation for the toggles, I'm glad you added that, it makes the UI feel much more cozy than compact.

**Comment by ZeusHay** [comment]
> I love this new update.

Thank you for supporting our development! :)

> Are you able to create an SXI bin folder for SXI instead of synapse? Just to save data in, you may be using that later on, for the rest of the toggles and stuff.

I've already had thoughts about adding this to the project in previous versions, but all of them I realized were not very good at saving this data, you know? so I'm thinking of some method to save it in a broader way, like json or database, and this I'll try to implement in the project as soon as possible :)

> I have noticed you've added something called Hydroxide. I have never seen this remote spy before and I am ashamed of myself for not seeing it. This remote spy is amazing and I will use it from now on instead of Frost Hook and Simple Spy.

This lua you are talking about is a project from user @Upbolt, who also has a project here on github:

https://github.com/Upbolt/Hydroxide

Thank you very much for evaluating our project <3
